[2024-12-04T23:13:47.532+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-04T23:13:47.541+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake manual__2024-12-04T23:04:20.456807+00:00 [queued]>
[2024-12-04T23:13:47.544+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake manual__2024-12-04T23:04:20.456807+00:00 [queued]>
[2024-12-04T23:13:47.544+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-12-04T23:13:47.547+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_tmdb_data_to_snowflake> on 2024-12-04 23:04:20.456807+00:00
[2024-12-04T23:13:47.550+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=75671) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-04T23:13:47.551+0000] {standard_task_runner.py:63} INFO - Started process 75674 to run task
[2024-12-04T23:13:47.550+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_tmdb_us_movies', 'load_tmdb_data_to_snowflake', 'manual__2024-12-04T23:04:20.456807+00:00', '--job-id', '800', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_historical.py', '--cfg-path', '/tmp/tmpw08xcltd']
[2024-12-04T23:13:47.551+0000] {standard_task_runner.py:91} INFO - Job 800: Subtask load_tmdb_data_to_snowflake
[2024-12-04T23:13:47.565+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake manual__2024-12-04T23:04:20.456807+00:00 [running]> on host bbf2723bdd9c
[2024-12-04T23:13:47.596+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_tmdb_us_movies' AIRFLOW_CTX_TASK_ID='load_tmdb_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T23:04:20.456807+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T23:04:20.456807+00:00'
[2024-12-04T23:13:47.597+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-04T23:13:47.600+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-12-04T23:13:47.601+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2024-12-04T23:13:47.601+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-04T23:13:48.135+0000] {logging_mixin.py:188} INFO - Starting transaction...
[2024-12-04T23:13:48.301+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-04T23:13:48.441+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-04T23:13:48.944+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-04T23:13:48.947+0000] {logging_mixin.py:188} INFO - Transaction rolled back due to error: 000904 (42000): 01b8d091-0004-4633-0002-edd30005266e: SQL compilation error: error line 20 at position 79
invalid identifier 'VOTE_AVERAGE'
[2024-12-04T23:13:48.948+0000] {connection.py:762} INFO - closed
[2024-12-04T23:13:49.002+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-12-04T23:13:49.110+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-04T23:13:49.118+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-04T23:13:49.136+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_tmdb_us_movies, task_id=load_tmdb_data_to_snowflake, run_id=manual__2024-12-04T23:04:20.456807+00:00, execution_date=20241204T230420, start_date=20241204T231347, end_date=20241204T231349
[2024-12-04T23:13:49.168+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-04T23:13:49.182+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T23:13:49.183+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
