[2024-12-04T23:04:24.054+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-04T23:04:24.068+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake scheduled__2024-12-04T21:00:00+00:00 [queued]>
[2024-12-04T23:04:24.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake scheduled__2024-12-04T21:00:00+00:00 [queued]>
[2024-12-04T23:04:24.072+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-12-04T23:04:24.077+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_tmdb_data_to_snowflake> on 2024-12-04 21:00:00+00:00
[2024-12-04T23:04:24.090+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=75250) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-04T23:04:24.089+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_tmdb_us_movies', 'load_tmdb_data_to_snowflake', 'scheduled__2024-12-04T21:00:00+00:00', '--job-id', '794', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_historical.py', '--cfg-path', '/tmp/tmplh_3vksr']
[2024-12-04T23:04:24.093+0000] {standard_task_runner.py:63} INFO - Started process 75259 to run task
[2024-12-04T23:04:24.094+0000] {standard_task_runner.py:91} INFO - Job 794: Subtask load_tmdb_data_to_snowflake
[2024-12-04T23:04:24.136+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake scheduled__2024-12-04T21:00:00+00:00 [running]> on host bbf2723bdd9c
[2024-12-04T23:04:24.200+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_tmdb_us_movies' AIRFLOW_CTX_TASK_ID='load_tmdb_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-04T21:00:00+00:00'
[2024-12-04T23:04:24.203+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-04T23:04:24.213+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-12-04T23:04:24.215+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2024-12-04T23:04:24.217+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-04T23:04:24.935+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-04T23:04:24.939+0000] {logging_mixin.py:188} INFO - Transaction rolled back due to error: 'SnowflakeConnection' object has no attribute 'begin'
[2024-12-04T23:04:24.941+0000] {connection.py:762} INFO - closed
[2024-12-04T23:04:25.007+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-12-04T23:04:25.166+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-04T23:04:25.170+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-04T23:04:25.207+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_tmdb_us_movies, task_id=load_tmdb_data_to_snowflake, run_id=scheduled__2024-12-04T21:00:00+00:00, execution_date=20241204T210000, start_date=20241204T230424, end_date=20241204T230425
[2024-12-04T23:04:25.292+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-04T23:04:25.370+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T23:04:25.373+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
